apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngrok
  namespace: piprojet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: piprojet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      serviceAccountName: ngrok
      containers:
        - name: ngrok
          image: ubuntu:22.04
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              apt-get update -qq && apt-get install -y curl unzip > /dev/null
              curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz | tar xz -C /usr/local/bin
              ngrok config add-authtoken $NGROK_AUTHTOKEN
              ngrok http frontend.piprojet.svc.cluster.local:80 --log=stdout --region=eu
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
          ports:
            - containerPort: 4040
              name: mgmt
          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
