apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: piprojet
spec:
  type: ClusterIP
  selector:
    app: ngrok
  ports:
    - name: management-ui
      port: 4040
      targetPort: 4040
