apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: piprojet
data:
  ML_SERVICE_BASE_URL: "http://m2-ml-service:8000"
  CORS_ALLOWED_ORIGINS: "http://frontend,http://localhost:80,http://192.168.1.200,https://venomous-smugness-ethically.ngrok-free.dev"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "ca.unitumgroup1@gmail.com"
  BILLING_APP_URL: "http://192.168.1.200"
