apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  namespace: piprojet
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
