apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_INSTALL_PLUGINS
              value: "grafana-piechart-panel"
          volumeMounts:
            - name: datasource-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboard-json
              mountPath: /var/lib/grafana/dashboards
            - name: alert-rules
              mountPath: /etc/grafana/provisioning/alerting
            - name: storage
              mountPath: /var/lib/grafana
      volumes:
        - name: datasource-config
          configMap:
            name: grafana-datasource
        - name: dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: dashboard-json
          configMap:
            name: grafana-dashboard-piprojet
        - name: alert-rules
          configMap:
            name: grafana-alert-rules
        - name: storage
          emptyDir: {}
