apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-configmap
  namespace: piprojet
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "PiProjet123"
  DB_USER: "root"
  PIB_STRICT_MODE: "false"
  SEED_PIB_DATA: "false"
  EXPORT_PIB_ARTIFACTS: "true"
