apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-proxy-config
  namespace: piprojet
data:
  nginx.conf: |
    events {}
    http {
      upstream ml_backend {
        server m2-ml-service.piprojet.svc.cluster.local:8000 weight=7 max_fails=2 fail_timeout=10s;
        server 4.165.180.231:8000 weight=3 max_fails=2 fail_timeout=10s;
      }
      server {
        listen 9000;
        location / {
          proxy_pass http://ml_backend;
          proxy_connect_timeout 3s;
          proxy_read_timeout 30s;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-proxy
  namespace: piprojet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-proxy
  template:
    metadata:
      labels:
        app: ml-proxy
    spec:
      containers:
        - name: ml-proxy
          image: nginx:alpine
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: ml-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: ml-proxy
  namespace: piprojet
spec:
  selector:
    app: ml-proxy
  ports:
    - port: 9000
      targetPort: 9000
