apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: piprojet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ngrok
          image: ngrok/ngrok:3-alpine
          imagePullPolicy: IfNotPresent
          args: ["http", "frontend:80", "--log=stdout", "--config=/etc/ngrok/ngrok.yml"]
          env:
            - name: NGROK_AUTHTOKEN
              valueFrom:
                secretKeyRef:
                  name: ngrok-secret
                  key: authtoken
          ports:
            - containerPort: 4040
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /api/status
              port: 4040
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/status
              port: 4040
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
