sonar.projectKey=com.example:pi-projet
sonar.projectName=Pi Projet - Unitum
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# JaCoCo coverage report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions (generated code, config)
sonar.exclusions=\
  **/entity/**,\
  **/dto/**,\
  **/config/DataInitializer.java,\
  **/*Application.java

sonar.test.exclusions=src/test/**
sonar.java.source=17
sonar.sourceEncoding=UTF-8
